/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnijni_testjni */

#ifndef _Included_com_example_jnijni_testjni
#define _Included_com_example_jnijni_testjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnijni_testjni
 * Method:    AddStr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnijni_testjni_AddStr
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
